---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAZUmaMp+UqoARRCtvVjhzbguKBT+z+BDw+KDPxWvkHA3PesYUc6JJeycFW4DWkMZOVlgdIVAlqpW0BV4ms8hHxN3D+PnAup1PC768RawYLEfOCnsAd3PyJARn8ix/VdF2qhCFv839yRUbSZ9XxWdRohaGUmzVSW5q9Fo3g64nvUFHDqyeDRVz1TZ5EgoYRiGnuzh5g9SdfMHXHYkHwt/89gVHtADTEdNpfyiG7Z0/aChNb79JgqLwfxRKJTv90l3U8vy8bg4Q8LxAIoN5lTDcBf6LycfJZKWc0pXL4n8cacyWMes5VRTVH8Tf9ieWHvMIO3GNTebyGwFe5oBGBqQiFr1LoQaltza7/4qP9CcEz0gySwWAeVPXnEImZRksgxH//7CqKpf9bE/yL8Ia5FfIVb66rl+/w7cJ2OPi47+z/huakkxGdrlvvCdH5dBL852AWRJMwGJJ+PAlk1CFyXr/Cp/hlIKHDqJD/fuHPuEnZKj4gJ2fLBVrCB+5ztT9locv7UjIZYtzTleigMr46PzUklnfCzNCweNhKwxxRzIxEzeof6zN851asTos32Cf4JZIad13VmfQMt7yr96u6XreHEYu8k9Lw7VDV73plErw1PnrqkUzZPIhR/eIB2tnxGzKKQhqHjc7lOrd7p/wjhlIow5R38B+SljEita5OTSREln6xzKShsHuTOPBqADTg08v4bgzXXx7dlSEYpzLJwO4WDQ==
    admin-user: AgBWOSOQnArbfEkWSGa2t2aRlPVpqpXJtR86tiwqUasL1hC/brVp/aMBIw0kXeQZzU9vaKK2mI2bDDPNLYn9x3A+eT/GFGKXPYfwmQ0YwE8rAIJn26H9rerC0338AkzCVhM0WRuc9gFNUbpKr0s6Zv/JTZ+Q96O08vO0c3w+FzfGWF2upWhVhgTS5T2bw7YeUnbR7oO7A8yNS0RmpHUBZWlDLKjxTSYTqrtxnhbP8p8FjMjtxo89/H47Cl1aB7ri+9GOK/r3maNm5rJ8/u4krDks1FfTvEhsF6E1H4IALpqzILDfs1C4MQElyX3xLcA+bGgDiUvUl7ZHAWW/SzmuiMqhiI9S1FW22kz1E1+rHsoWdX9/mt/tYHQYzftihg25enRmJ3fxxcQHJKE2kuu2G7cnYWPY1EsgG1ckkScFLw4hErNJ/YuMCDafrMpG5Lr4nzUOZuRNdj+LxxmoxcKd0071MgyyRKsPRbiQa2D+6zG5u16saFmtiSTeMV+6I6L9s9ztXlrYYdf/jOxPezofprzRVw8yxhvPByGgZPk33Cjilym1TliTWzMZa25B+PQBNSCfVLyvk4I9E8fHGWLXEVwDef5yAwzL3rPqocdp58czzT3u765SeQagnasVRzF8eM+e9bv89yGvuFgIhTVrWdbkpd1LZimoarAc77Vt2IjlRMQcTeO+0dKzzuee48C7tt8TfLTp3Q==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
