apiVersion: v1
kind: ResourceQuota
metadata:
  name: apps-quota
  namespace: apps
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 6Gi
    limits.cpu: "5"
    limits.memory: 12Gi
    pods: "30"
