apiVersion: v1
kind: ResourceQuota
metadata:
  name: logging-quota
  namespace: logging
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 7Gi
    limits.cpu: "2"
    limits.memory: 7Gi
    pods: "15"
