apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "2"
    limits.memory: 3Gi
    pods: "15"
