apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: cicd
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "100m"
      memory: 128Mi
    default:
      cpu: "300m"
      memory: 256Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: "50m"
      memory: 64Mi
