- name: Initialize Kubernetes master
  hosts: master
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Run kubeadm init
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_output

    - name: Setup kubeconfig for user
      become: yes
      shell: |
        mkdir -p /home/{{ ansible_user }}/.kube
        cp -f /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
        chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config
      args:
        executable: /bin/bash

    - name: Get join command
      command: kubeadm token create --print-join-command
      register: join_cmd
      changed_when: false

    - debug:
        msg: "Use this join command on workers: {{ join_cmd.stdout }}"
