name: homelab-cicd

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/nginx-test:$(date +%Y%m%d%H%M%S)
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE ./apps/nginx-test
          docker push $IMAGE

      - name: Update manifest with new image
        run: |
          sed -i "s|image: .*|image: $IMAGE|" apps/nginx-test.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "chore: update nginx-test image $IMAGE"
          git push
